# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 16:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descpition', models.CharField(default='江湖第一美人', max_length=200, verbose_name='个性签名')),
                ('job', models.CharField(default='美人', max_length=200, verbose_name='工作')),
                ('phone', models.CharField(default='12345678910', max_length=15, verbose_name='手机')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='头像图像')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='发布时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
