# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrative_division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='行政区域')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='装修质量')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'layout',
                'verbose_name_plural': 'Layouts',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'cumpus',
                'verbose_name_plural': 'cumpies',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='城市')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('distance', models.CharField(db_index=True, max_length=200, verbose_name='与校区距离')),
                ('campus', models.ManyToManyField(related_name='campus_locate', to='shop.Campus')),
                ('locations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lactional', to='shop.Administrative_division')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'device',
                'verbose_name_plural': 'devices',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='商品名')),
                ('slug', models.SlugField(max_length=200, verbose_name='链接地址')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='商品图像')),
                ('bedroom', models.IntegerField(verbose_name='卧室数量')),
                ('living_room', models.IntegerField(default=0, verbose_name='卧室数量')),
                ('tolet', models.IntegerField(default=1, verbose_name='卫生间数量')),
                ('orientations', models.CharField(default='朝南', max_length=20, verbose_name='房间朝向')),
                ('height', models.IntegerField(default=0, verbose_name='房间层高')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('stock', models.PositiveIntegerField(verbose_name='库存')),
                ('available', models.BooleanField(default=True, verbose_name='是否上架')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='发布时间')),
                ('apartment_layout', models.ManyToManyField(related_name='apartment', to='shop.ApartmentLayout')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.Category')),
                ('device', models.ManyToManyField(related_name='device', to='shop.Device')),
                ('locate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_locate', to='shop.City')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Updown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='小区名称')),
                ('address', models.CharField(db_index=True, max_length=300, verbose_name='详细地址')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'cities',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='administrative_division',
            name='updown',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updown_locate', to='shop.Updown'),
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together=set([('id', 'slug')]),
        ),
    ]
